project:
  type: website

website:
  title: "Project CLIMATE in Sri Lanka"
  site-url: "https://project-climate-bassconnections.github.io/"
  navbar:
    logo: images/logo-farmworkers-only.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: team.qmd
        text: Meet the Team
      - href: articles.qmd
        text: Articles
  page-footer: 
    right: "Copyright 2025, Site created by Natasha Harris"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    grid:
      body-width: 1000px

editor: source