project:
  type: website

website:
  title: "Project CLIMATE in Sri Lanka"
  navbar:
    logo: images/logo-farmworkers-only.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - team.qmd
      - articles.qmd
  page-footer: 
    right: "Copyright 2025, Site created by Natasha Harris"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    grid:
      body-width: 1000px

editor: source

